### ISSUE TITLE
Crash with pack

### ISSUE THREAD

**Issue by Trollebas** [anatawa12/fixRTM#92]
My used pack: https://www.dropbox.com/s/cdvogw847ghg8oc/pack.zip?dl=0
[crash-2020-05-31_00.27.22-client.txt](https://github.com/anatawa12/fixRTM/files/4706563/crash-2020-05-31_00.27.22-client.txt)
RTM 2.4.19, fixRtm-2.0.10

**Comment by anatawa12** [comment]
looks your pack (Trollebas_Pack-1.2.3.zip) is not valid. On some path in your pack, there are some invalid characters. that's the reason for the crash. However I found a bug. the bug is that the message of the crash report is not I expected. I will fix the bug and I will close this issue.
